#!/usr/bin/env python3
"""generate-smoke-script.py - turn a Smoke manifest v1 into a runnable smoke script.

Usage: generate-smoke-script.py <manifest.yaml> <output-script.sh>

Reads the fields defined in the toolkit interface spec, maintainers/toolkit-interface-spec.md,
section 5 ("smoke: v1"): target, assertions.{identity,freshness,connections,routes,
console}. It never invents fields the spec does not define; the field list lives only
in the spec.

The emitted script is self-contained bash (curl + bash's own /dev/tcp; no python at
run time) so it can be committed to a project and run without this skill installed.
Every check category can be forced to fail independently via an environment-variable
override, which is how scripts/run-poison-proof.sh and fixtures/run-fixture-proof.
FIXTURE.sh prove each category one at a time without touching the manifest file:

    SMOKE_TARGET                              overrides target
    SMOKE_IDENTITY_EXPECT                     overrides assertions.identity.expect
    SMOKE_FRESHNESS_STALE                     overrides assertions.freshness.must_advance_from
    SMOKE_CONN_HOST_<NAME> / SMOKE_CONN_PORT_<NAME>
                                               host/port to TCP-check for connection <NAME>
                                               (required; the manifest shape carries no
                                               address field for connections, only a name)
    SMOKE_ROUTE_PATH_<PATH>                   overrides the path checked for route <PATH>
    SMOKE_CONSOLE_MARKER                      overrides the console error-marker string
    SMOKE_CONSOLE_SOURCE                      file to scan for the marker instead of
                                               re-fetching target (a saved browser
                                               console log in a real deployment)

<NAME> and <PATH> are the connection name / route path, non-alphanumeric characters
replaced with "_", upper-cased.

A manifest whose assertion category (identity, freshness, connections, routes, or
console) has no matching "poison" entry is refused at generation time (exit 1,
"UNPROVEN <category>: no poison entry"), never generated with an empty or missing
poison value: a category the generator never proved could fail would otherwise report
PASS on every run, which the spec (section 5) forbids ("a category with no poison
entry is not proven and the gate reports it as unproven, never as passed"). Add the
missing poison.<category> entry before generating.
"""
import os
import re
import shlex
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("generate-smoke-script.py: PyYAML is required (pip install pyyaml)\n")
    sys.exit(1)


def die(msg):
    sys.stderr.write(f"generate-smoke-script.py: {msg}\n")
    sys.exit(1)


def require_poison(category, poison):
    """Refuse to generate a script for a category the manifest never proves can fail.
    Per interface spec section 5, every assertion category present in the manifest
    must carry a poison entry; a category with none is reported unproven, never
    generated with a default that would silently pass forever."""
    if poison.get(category) in (None, ""):
        die(f"UNPROVEN {category}: no poison entry")


def var_name(s):
    return re.sub(r"[^A-Za-z0-9]", "_", s).strip("_").upper() or "X"


def dq(s):
    """Escape a value for embedding inside an already-double-quoted bash default,
    e.g. "${VAR:-<dq(value)>}". Do not wrap it in its own quotes (shlex.quote's
    single-quote wrapping is wrong here: nested inside an outer double-quoted
    string, literal single quotes are not quoting, they are just characters)."""
    s = str(s)
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def main():
    if len(sys.argv) != 3:
        die("usage: generate-smoke-script.py <manifest.yaml> <output-script.sh>")
    manifest_path, out_path = sys.argv[1], sys.argv[2]

    with open(manifest_path, encoding="utf-8") as f:
        m = yaml.safe_load(f)

    if not isinstance(m, dict) or m.get("smoke") != "v1":
        die(f"manifest does not declare 'smoke: v1' (got {m.get('smoke') if isinstance(m, dict) else m!r})")
    if "target" not in m:
        die("manifest missing required field 'target'")

    target = m["target"]
    a = m.get("assertions", {}) or {}
    poison = m.get("poison", {}) or {}

    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append("# GENERATED by verification-kit:smoke-gate scripts/generate-smoke-script.py")
    lines.append(f"# source manifest: {os.path.basename(manifest_path)} (Smoke manifest v1)")
    lines.append("# Do not hand-edit. Regenerate from the manifest instead.")
    lines.append("set -uo pipefail")
    lines.append(f'TARGET="${{SMOKE_TARGET:-{shlex.quote(str(target))}}}"')
    lines.append("FAILED_CATEGORIES=()")
    lines.append("")

    if "identity" in a:
        require_poison("identity", poison)
        expect = a["identity"]["expect"]
        lines += [
            "# --- identity ---",
            f'IDENTITY_EXPECT="${{SMOKE_IDENTITY_EXPECT:-{dq(expect)}}}"',
            'BODY_IDENTITY="$(curl -sS "$TARGET" || true)"',
            'if printf "%s" "$BODY_IDENTITY" | grep -qF -- "$IDENTITY_EXPECT"; then',
            '  echo "PASS identity: found \\"$IDENTITY_EXPECT\\" on $TARGET"',
            "else",
            '  echo "FAIL identity: expected \\"$IDENTITY_EXPECT\\" not found on $TARGET"',
            "  FAILED_CATEGORIES+=(identity)",
            "fi",
            "",
        ]

    if "freshness" in a:
        require_poison("freshness", poison)
        field = a["freshness"]["field"]
        stale = a["freshness"]["must_advance_from"]
        lines += [
            "# --- freshness ---",
            f"FRESH_FIELD={shlex.quote(str(field))}",
            f'FRESH_STALE="${{SMOKE_FRESHNESS_STALE:-{dq(stale)}}}"',
            'BODY_FRESH="$(curl -sS "$TARGET" || true)"',
            'FRESH_LINE="$(printf "%s" "$BODY_FRESH" | grep -F "$FRESH_FIELD" | head -1)"',
            'FRESH_VALUE="$(printf "%s" "$FRESH_LINE" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | head -1)"',
            'if [ -n "$FRESH_VALUE" ] && [[ "$FRESH_VALUE" > "$FRESH_STALE" ]]; then',
            '  echo "PASS freshness: $FRESH_FIELD=$FRESH_VALUE advanced past $FRESH_STALE"',
            "else",
            '  echo "FAIL freshness: $FRESH_FIELD=${FRESH_VALUE:-<not found>} did not advance past $FRESH_STALE"',
            "  FAILED_CATEGORIES+=(freshness)",
            "fi",
            "",
        ]

    if "connections" in a:
        require_poison("connections", poison)
        for c in a["connections"]:
            name = c["name"]
            v = var_name(name)
            lines += [
                f"# --- connections: {name} ---",
                f'CONN_HOST_{v}="${{SMOKE_CONN_HOST_{v}:?set SMOKE_CONN_HOST_{v} to the host to check for connection \\"{name}\\"}}"',
                f'CONN_PORT_{v}="${{SMOKE_CONN_PORT_{v}:?set SMOKE_CONN_PORT_{v} to the port to check for connection \\"{name}\\"}}"',
                f'if timeout 2 bash -c "cat < /dev/null > /dev/tcp/$CONN_HOST_{v}/$CONN_PORT_{v}" 2>/dev/null; then',
                f'  echo "PASS connections:{name}: $CONN_HOST_{v}:$CONN_PORT_{v} open"',
                "else",
                f'  echo "FAIL connections:{name}: $CONN_HOST_{v}:$CONN_PORT_{v} not reachable"',
                "  FAILED_CATEGORIES+=(connections)",
                "fi",
                "",
            ]

    if "routes" in a:
        require_poison("routes", poison)
        for r in a["routes"]:
            path = r["path"]
            status = r["status"]
            v = var_name(path)
            lines += [
                f"# --- routes: {path} ---",
                f'ROUTE_PATH_{v}="${{SMOKE_ROUTE_PATH_{v}:-{dq(path)}}}"',
                f'ROUTE_CODE_{v}="$(curl -sS -o /dev/null -w "%{{http_code}}" "$TARGET$ROUTE_PATH_{v}" || echo 000)"',
                f'if [ "$ROUTE_CODE_{v}" = "{status}" ]; then',
                f'  echo "PASS routes:$ROUTE_PATH_{v}: status $ROUTE_CODE_{v}"',
                "else",
                f'  echo "FAIL routes:$ROUTE_PATH_{v}: expected {status} got $ROUTE_CODE_{v}"',
                "  FAILED_CATEGORIES+=(routes)",
                "fi",
                "",
            ]

    if "console" in a:
        require_poison("console", poison)
        marker_default = poison.get("console")
        lines += [
            "# --- console ---",
            "# FIXTURE-mode stand-in: a real console-error check needs a browser (the Browser",
            "# tool or Playwright, per Anthropic's webapp-testing skill) to read the DevTools",
            "# console. This generic check greps a text source for a known error marker",
            "# instead. Point SMOKE_CONSOLE_SOURCE at a captured browser console log in a real",
            "# deployment; it falls back to re-fetching target, which is only valid for a",
            "# fixture target that echoes the marker into its own page body.",
            f'CONSOLE_MARKER="${{SMOKE_CONSOLE_MARKER:-{dq(marker_default)}}}"',
            'CONSOLE_SOURCE="${SMOKE_CONSOLE_SOURCE:-}"',
            'if [ -n "$CONSOLE_SOURCE" ]; then',
            '  BODY_CONSOLE="$(cat "$CONSOLE_SOURCE" 2>/dev/null || true)"',
            "else",
            '  BODY_CONSOLE="$(curl -sS "$TARGET" || true)"',
            "fi",
            'if [ -n "$CONSOLE_MARKER" ] && printf "%s" "$BODY_CONSOLE" | grep -qF -- "$CONSOLE_MARKER"; then',
            '  echo "FAIL console: marker \\"$CONSOLE_MARKER\\" found (treated as a console error)"',
            "  FAILED_CATEGORIES+=(console)",
            "else",
            '  echo "PASS console: no error marker found"',
            "fi",
            "",
        ]

    lines += [
        "if [ ${#FAILED_CATEGORIES[@]} -gt 0 ]; then",
        '  echo "SMOKE FAIL: ${FAILED_CATEGORIES[*]}"',
        "  exit 1",
        "fi",
        'echo "SMOKE PASS: all categories green"',
        "exit 0",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(out_path, 0o755)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
