"""Shared frontmatter parsing and inventory rendering for skill-library scripts.

Single editable home for this logic: validate-skills.sh and generate-inventory.sh
both import it. A second copy of the parser is drift, not convenience.
"""
import os
import re


def parse_frontmatter(text):
    """Minimal YAML-subset parser: scalars, one nested map level, >-/|/> blocks."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    data, ctx = {}, None  # ctx = name of open nested map
    block_key, block_lines, block_ctx, block_indent = None, [], None, -1
    for line in text[3:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        if block_key is not None:
            if indent > block_indent:
                block_lines.append(line.strip())
                continue
            tgt = data[block_ctx] if block_ctx else data
            tgt[block_key] = " ".join(block_lines)
            block_key, block_lines, block_ctx = None, [], None
        m = re.match(r"^(\s*)([\w.-]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(2), m.group(3).strip()
        if indent == 0:
            ctx = None
        if val in (">-", ">", "|", "|-"):
            block_key, block_ctx, block_indent = key, ctx, indent
        elif val == "":
            if indent == 0:
                data[key], ctx = {}, key
            else:
                (data[ctx] if ctx else data)[key] = ""
        else:
            val = val.strip("'\"")
            if indent == 0:
                data[key] = val
            elif ctx:
                data[ctx][key] = val
    if block_key is not None:
        tgt = data[block_ctx] if block_ctx else data
        tgt[block_key] = " ".join(block_lines)
    return data, text[end + 4:]


def skill_rows(root="plugins"):
    """One dict per skill directory under plugins/*/skills/*, sorted by path."""
    rows = []
    for plugin in sorted(os.listdir(root)) if os.path.isdir(root) else []:
        sp = os.path.join(root, plugin, "skills")
        if not os.path.isdir(sp):
            continue
        for s in sorted(os.listdir(sp)):
            d = os.path.join(sp, s)
            sk = os.path.join(d, "SKILL.md")
            if not os.path.isdir(d) or not os.path.isfile(sk):
                continue
            parsed = parse_frontmatter(
                open(sk, encoding="utf-8", errors="replace").read())
            if not parsed:
                continue
            fm, _ = parsed
            meta = fm.get("metadata") if isinstance(fm.get("metadata"), dict) else {}
            rows.append({
                "name": str(fm.get("name", "")).strip() or s,
                "plugin": plugin,
                "maturity": str(meta.get("maturity", "")).strip(),
                "version": str(meta.get("version", "")).strip(),
                "description": re.sub(r"\s+", " ",
                                      str(fm.get("description", "")).strip()),
            })
    return rows


def render_inventory(rows):
    """The docs/inventory.md content. Deterministic: no timestamps, so the
    validator's staleness check is a plain string comparison."""
    lines = [
        "# Skill inventory",
        "",
        "Generated by `scripts/generate-inventory.sh`. Do not edit by hand; the",
        "validator fails (F13) when this file is stale. One line per skill, so a",
        "single fetch tells a remote session everything the library holds.",
        "",
        "| name | plugin | maturity | version | description |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        desc = r["description"].replace("|", "\\|")
        lines.append("| {name} | {plugin} | {maturity} | {version} | {d} |".format(
            d=desc, **{k: r[k] for k in ("name", "plugin", "maturity", "version")}))
    lines.append("")
    return "\n".join(lines)
