#!/usr/bin/env python3
"""generate-pack-map.py: draw docs/images/pack-map.svg, the map of the packs.

Sources: .claude-plugin/marketplace.json (which packs, in what order), each
plugins/<pack>/.claude-plugin/plugin.json (its `dependencies`), and the plugins/ tree
(skill and agent counts, through scripts/skill_meta.py). Edit a source and run this,
never the image.

Usage: python3 maintainers/scripts/generate-pack-map.py          # regenerate
       python3 maintainers/scripts/generate-pack-map.py --check  # exit 1 if the image is stale
"""
import json
import os
import sys
from xml.sax.saxutils import escape

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from skill_meta import pack_counts, pack_dependencies  # noqa: E402

OUT = os.path.join("docs", "images", "pack-map.svg")
WIDTH, MARGIN, BOX_H = 960, 18, 64

STYLE = """
    .surface { fill: #fcfcfb; }
    .box { fill: #ffffff; stroke: #52514e; stroke-width: 1.5; }
    .base { stroke: #2a78d6; stroke-width: 2.5; }
    .edge { stroke: #2a78d6; stroke-width: 2; fill: none; }
    .head { fill: #2a78d6; }
    .name { font: 600 14px -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; fill: #0b0b0b; }
    .count, .note { font: 12px -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; fill: #52514e; }
    .row { font: 600 13px -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; fill: #0b0b0b;
           stroke: #fcfcfb; stroke-width: 6px; paint-order: stroke; stroke-linejoin: round; }
    @media (prefers-color-scheme: dark) {
      .surface { fill: #1a1a19; }
      .box { fill: #262624; stroke: #c3c2b7; }
      .base, .edge { stroke: #3987e5; }
      .head { fill: #3987e5; }
      .name, .row { fill: #ffffff; }
      .row { stroke: #1a1a19; }
      .count, .note { fill: #c3c2b7; }
    }
"""


def load():
    with open(os.path.join(ROOT, ".claude-plugin", "marketplace.json"), encoding="utf-8") as f:
        names = [p["name"] for p in json.load(f)["plugins"]]
    counts = pack_counts(os.path.join(ROOT, "plugins"))
    return names, counts, pack_dependencies(names, os.path.join(ROOT, "plugins"))


def count_label(skills, agents):
    text = f"{skills} skill" + ("s" if skills != 1 else "")
    if agents:
        text += f", {agents} agent" + ("s" if agents != 1 else "")
    return text


def row_boxes(names, y):
    """Evenly spaced boxes across the width: {name: (x, y, w)}."""
    gap = 12
    w = (WIDTH - 2 * MARGIN - gap * (len(names) - 1)) / len(names)
    return {n: (MARGIN + i * (w + gap), y, w) for i, n in enumerate(names)}


def render():
    names, counts, deps = load()
    needed = sorted({d for ds in deps.values() for d in ds})
    unknown = [d for d in needed if d not in names]
    if unknown:
        sys.exit(f"PROBLEM: a pack depends on {unknown}, not in marketplace.json")
    if any(deps[b] for b in needed):
        sys.exit("PROBLEM: a depended-on pack has its own dependency; the map draws one level only")
    dependents = [n for n in names if deps[n]]
    alone = [n for n in names if not deps[n] and n not in needed]

    boxes = {}
    base_w = 220
    for i, n in enumerate(needed):
        span = len(needed) * base_w + (len(needed) - 1) * 12
        boxes[n] = ((WIDTH - span) / 2 + i * (base_w + 12), 52, base_w)
    boxes.update(row_boxes(dependents, 190))
    boxes.update(row_boxes(alone, 322))
    height = 322 + BOX_H + 46

    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {height}" '
           f'width="{WIDTH}" height="{height}" role="img" aria-labelledby="t d">',
           "  <!-- generated by maintainers/scripts/generate-pack-map.py from "
           ".claude-plugin/marketplace.json, the plugin.json files and the plugins/ tree; "
           "edit the source, never this file -->",
           '  <title id="t">Map of the packs in skill-library</title>']
    desc = (f"{len(names)} packs. "
            + "; ".join(f"{', '.join(dependents)} each need {b}, which Claude Code installs "
                        "with them" for b in needed)
            + f". {', '.join(alone)} install on their own.")
    out.append(f'  <desc id="d">{escape(desc)}</desc>')
    out.append(f"  <style>{STYLE}  </style>")
    out.append(f'  <rect class="surface" width="{WIDTH}" height="{height}" rx="8"/>')

    for n in dependents:
        x, y, w = boxes[n]
        for b in deps[n]:
            bx, by, bw = boxes[b]
            out.append(f'  <path class="edge" d="M {x + w / 2:.1f} {y} V 146 '
                       f'H {bx + bw / 2:.1f} V {by + BOX_H + 9}"/>')
    for b in needed:
        bx, by, bw = boxes[b]
        cx, tip = bx + bw / 2, by + BOX_H + 1
        out.append(f'  <path class="head" d="M {cx:.1f} {tip} l -6 10 h 12 z"/>')

    # after the edges, so a label's halo covers the line it crosses
    out.append(f'  <text class="row" x="{MARGIN}" y="32">The base pack</text>')
    out.append(f'  <text class="row" x="{MARGIN}" y="176">Packs that need the base pack '
               "(Claude Code installs it with them)</text>")
    out.append(f'  <text class="row" x="{MARGIN}" y="308">Packs that install on their own</text>')

    for n in names:
        x, y, w = boxes[n]
        cls = "box base" if n in needed else "box"
        out.append(f'  <rect class="{cls}" x="{x:.1f}" y="{y}" width="{w:.1f}" '
                   f'height="{BOX_H}" rx="6"/>')
        out.append(f'  <text class="name" x="{x + w / 2:.1f}" y="{y + 27}" '
                   f'text-anchor="middle">{escape(n)}</text>')
        out.append(f'  <text class="count" x="{x + w / 2:.1f}" y="{y + 47}" '
                   f'text-anchor="middle">{count_label(*counts[n])}</text>')

    total_s = sum(counts[n][0] for n in names)
    total_a = sum(counts[n][1] for n in names)
    out.append(f'  <text class="note" x="{MARGIN}" y="{height - 16}">{len(names)} packs, '
               f"{total_s} skills, {total_a} agents. An arrow points from a pack to the pack "
               "it needs.</text>")
    out.append("</svg>")
    return "\n".join(out) + "\n"


def main():
    os.chdir(ROOT)
    text = render()
    if sys.argv[1:] == ["--check"]:
        if not os.path.isfile(OUT) or open(OUT, encoding="utf-8").read() != text:
            print(f"STALE: {OUT} does not match its sources. "
                  "Run: python3 maintainers/scripts/generate-pack-map.py")
            sys.exit(1)
        print(f"{OUT} is current")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
